name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test
    - name: Publish
      run: dotnet publish src -c Release -o publish
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: HLib artifacts
        path: publish
